
server:
  port: ${PORT:8080}
  error:
    include-message: always

spring:
  application:
    name: camarena-backend

  # CONFIGURACIÓN DE BASE DE DATOS (PostgreSQL)
  datasource:

    url: ${DB_URL:jdbc:postgresql://localhost:5432/camarena_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:0102}
    driver-class-name: org.postgresql.Driver

  # CONFIGURACIÓN DE JPA / HIBERNATE
  jpa:
    # En producción real esto suele cambiarse a 'validate'.
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# VARIABLES PERSONALIZADAS DEL LABORATORIO (Camarena Digital)

camarena:
  security:
    jwt:
      secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration-ms: ${JWT_EXPIRATION:86400000}


# Configuración exacta para APIsPERU
api:
  reniec:
    url: https://dniruc.apisperu.com/api/v1/dni
    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImppdHNiZW43QGdtYWlsLmNvbSJ9.dNzOGYpufApD1WqlLQ1cUM801ZeWABEVO4WN36hVUsM